### ISSUE TITLE
Path directories

### ISSUE THREAD

**Issue by ahx-code** [TenninYan/quantum-mnist#2]
Dear @TenninYan 

Under [get_ptrace_data](https://github.com/TenninYan/quantum-mnist/blob/a8c98578341e5634b8e9d7b705ad3aab4f980c25/cca_nn_classifier.py#L292) method, both train and test paths are set to the same directory. Is it mistakenly set? 

Thanks and Regards

**Comment by TenninYan** [comment]
Hi @AhmetTavli 

You are right! It was my mistake
