### ISSUE TITLE
Unable to get API Key

### ISSUE THREAD

**Issue by ahx-code** [TenninYan/quantum-mnist#3]
Dear @TenninYan 

When I visit the [forest.rigetti](http://forest.rigetti.com/), the website gives an error.

Then I visit the following [website](https://qcs.rigetti.com/request-access), however, I haven't received an API key.

If possible, will you share an API key with me? If you agree with me, will you (ahmet.tavli@ozu.edu.tr) me FOREST_API_KEY and user_id? 

Regards

**Comment by TenninYan** [comment]
@AhmetTavli Ask Rigetti for their API Key!
